PREFIX state: <https://fireforce6.github.io/sierra/state#>
PREFIX base: <https://fireforce6.github.io/sierra/base#>
PREFIX oml: <http://opencaesar.io/oml#>

SELECT DISTINCT ?FromState ?ToState ?Trigger
WHERE {
    ?trans a state:Transition ;
           oml:hasSource ?src ;
           oml:hasTarget ?tgt ;
           state:isTriggeredBy ?trig .
           
    ?src base:description ?FromState .
    ?tgt base:description ?ToState .
    ?trig base:description ?Trigger .
}